"""
Thesis Figures Generator
Subgroup Analysis - Synthetic Survey Generation for Life Satisfaction Research

This script generates publication-quality figures for presenting
subgroup analysis findings in a clear, informative manner.

Note: Tables are generated by subgroup_analysis.py
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from scipy.stats import f_oneway
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

# ============================================================================
# Path Configuration
# ============================================================================
SCRIPT_DIR = Path(__file__).parent
BASE_DIR = SCRIPT_DIR.parent.parent  # Thesis/
DATA_DIR = BASE_DIR / "Outputs" / "metrics_tables" / "subgroup_analysis"
FIGURES_DIR = BASE_DIR / "Outputs" / "plots" / "subgroup_analysis"

FIGURES_DIR.mkdir(parents=True, exist_ok=True)

# Set publication-quality style
plt.style.use('seaborn-v0_8-paper')
sns.set_palette("husl")

# Custom color schemes - matching your existing plots.ipynb
COUNTRY_COLORS = {'USA': '#1f77b4', 'IDN': '#ff7f0e', 'NLD': '#2ca02c', 'MEX': '#d62728'}
MODEL_COLORS = {'llama3.1_8b': '#2ecc71', 'llama3.3_70b': '#3498db', 'qwen2.5_72b': '#e74c3c'}
HEALTH_COLORS = {'Good': '#2ecc71', 'Fair': '#f39c12', 'Poor': '#e74c3c'}

# Questionnaire colors - from your plots.ipynb LINE_COLORS
QUESTIONNAIRE_COLORS = {
    'base': '#58C747D9',        # Original WVS (green)
    'reverse': '#ff7e0ecd',     # Reverse (orange)
    'cantril': '#66aada',       # Cantril (blue)
    'swls': '#9c27d696',        # SWLS (purple)
    'ohq': '#ff5722',           # OHQ/OHS (red-orange)
}

# Load data
print("Loading data...")
df_all = pd.read_csv(DATA_DIR / 'all_segment_metrics.csv')
# Use only segment-level (Full) data for variance decomposition and summary statistics
df = df_all[df_all['level'] == 'Full'].copy()
print(f"  Using {len(df)} segment-level (Full) rows for analysis")
segment_insights = pd.read_csv(DATA_DIR / 'segment_insights.csv')
model_perf = pd.read_csv(DATA_DIR / 'model_performance.csv')
questionnaire_perf = pd.read_csv(DATA_DIR / 'questionnaire_performance.csv')

# ============================================================================
# FIGURE 1: Comprehensive Heatmap Matrix
# ============================================================================
print("\nGenerating Figure 1: Comprehensive Heatmap Matrix...")

def create_comprehensive_heatmap():
    """
    Create a multi-panel heatmap showing Wasserstein distances across all factors.
    This replaces the less informative line plots.
    """
    # Use full-level segments (df is already filtered to Full level)
    full_df = df.copy()

    fig, axes = plt.subplots(2, 2, figsize=(16, 14))
    fig.suptitle('Approximation Quality Across Demographic Subgroups\n(Wasserstein Distance)',
                 fontsize=16, fontweight='bold', y=0.995)

    # Panel A: Country × Health (averaged across income and models)
    ax1 = axes[0, 0]
    pivot1 = full_df.groupby(['country', 'health_level'])['wasserstein'].mean().reset_index()
    pivot1 = pivot1.pivot(index='health_level', columns='country', values='wasserstein')
    pivot1 = pivot1.reindex(['Good', 'Fair', 'Poor'])  # Order health levels

    sns.heatmap(pivot1, annot=True, fmt='.2f', cmap='RdYlGn_r',
                vmin=0.5, vmax=3.0, ax=ax1, cbar_kws={'label': 'Wasserstein Distance'},
                linewidths=0.5, linecolor='gray')
    ax1.set_title('(A) Country × Health Status', fontsize=12, fontweight='bold', pad=10)
    ax1.set_xlabel('Country', fontsize=11)
    ax1.set_ylabel('Health Status', fontsize=11)

    # Panel B: Model × Questionnaire (averaged across demographics)
    ax2 = axes[0, 1]
    model_quest = df_all[df_all['level'].isin(['Overall', 'Country'])].copy()
    pivot2 = model_quest.groupby(['model', 'questionnaire'])['wasserstein'].mean().reset_index()
    pivot2 = pivot2.pivot(index='questionnaire', columns='model', values='wasserstein')
    pivot2 = pivot2[['llama3.1_8b', 'llama3.3_70b', 'qwen2.5_72b']]  # Order models

    sns.heatmap(pivot2, annot=True, fmt='.2f', cmap='RdYlGn_r',
                vmin=0.5, vmax=3.5, ax=ax2, cbar_kws={'label': 'Wasserstein Distance'},
                linewidths=0.5, linecolor='gray')
    ax2.set_title('(B) Model × Questionnaire Type', fontsize=12, fontweight='bold', pad=10)
    ax2.set_xlabel('Model', fontsize=11)
    ax2.set_ylabel('Questionnaire Type', fontsize=11)
    ax2.set_xticklabels(['LLaMA 3.1 8B', 'LLaMA 3.3 70B', 'Qwen 2.5 72B'], rotation=45, ha='right')

    # Panel C: Income × Health (averaged across countries and models)
    ax3 = axes[1, 0]
    pivot3 = full_df.groupby(['income_level', 'health_level'])['wasserstein'].mean().reset_index()
    pivot3 = pivot3.pivot(index='health_level', columns='income_level', values='wasserstein')
    pivot3 = pivot3.reindex(['Good', 'Fair', 'Poor'])  # Order health
    pivot3 = pivot3[['Low', 'Medium', 'High']]  # Order income

    sns.heatmap(pivot3, annot=True, fmt='.2f', cmap='RdYlGn_r',
                vmin=1.0, vmax=3.0, ax=ax3, cbar_kws={'label': 'Wasserstein Distance'},
                linewidths=0.5, linecolor='gray')
    ax3.set_title('(C) Income × Health Status', fontsize=12, fontweight='bold', pad=10)
    ax3.set_xlabel('Income Level', fontsize=11)
    ax3.set_ylabel('Health Status', fontsize=11)

    # Panel D: Country-specific model performance
    ax4 = axes[1, 1]
    country_model = df_all[df_all['level'] == 'Country'].copy()
    pivot4 = country_model.groupby(['country', 'model'])['wasserstein'].mean().reset_index()
    pivot4 = pivot4.pivot(index='model', columns='country', values='wasserstein')
    pivot4 = pivot4.reindex(['llama3.1_8b', 'llama3.3_70b', 'qwen2.5_72b'])

    sns.heatmap(pivot4, annot=True, fmt='.2f', cmap='RdYlGn_r',
                vmin=0.8, vmax=2.5, ax=ax4, cbar_kws={'label': 'Wasserstein Distance'},
                linewidths=0.5, linecolor='gray')
    ax4.set_title('(D) Model Performance by Country', fontsize=12, fontweight='bold', pad=10)
    ax4.set_xlabel('Country', fontsize=11)
    ax4.set_ylabel('Model', fontsize=11)
    ax4.set_yticklabels(['LLaMA 3.1 8B', 'LLaMA 3.3 70B', 'Qwen 2.5 72B'], rotation=0)

    plt.tight_layout()
    plt.savefig(FIGURES_DIR / 'fig1_comprehensive_heatmap.png', dpi=300, bbox_inches='tight')
    plt.savefig(FIGURES_DIR / 'fig1_comprehensive_heatmap.pdf', bbox_inches='tight')
    print("  ✓ Saved: fig1_comprehensive_heatmap.png/pdf")
    plt.close()

create_comprehensive_heatmap()

# ============================================================================
# FIGURE 2: Variance Decomposition Forest Plot
# ============================================================================
print("\nGenerating Figure 2: Variance Decomposition Forest Plot...")

def create_variance_decomposition_plot():
    """
    Create a bar plot showing variance explained by each factor.
    Uses proper Sum of Squares decomposition for variance explained calculation.
    """
    # Calculate variance explained for each factor using Sum of Squares approach
    factors = ['health_level', 'income_level', 'country', 'model', 'questionnaire']
    factor_names = ['Health Status', 'Income Level', 'Country', 'Model', 'Questionnaire Type']

    results = []
    grand_mean = df['wasserstein'].mean()

    # Total Sum of Squares
    SS_total = ((df['wasserstein'] - grand_mean) ** 2).sum()

    for factor, name in zip(factors, factor_names):
        # Between-group Sum of Squares: sum of n_i * (group_mean_i - grand_mean)^2
        group_stats = df.groupby(factor)['wasserstein'].agg(['mean', 'count'])
        SS_between = ((group_stats['mean'] - grand_mean) ** 2 * group_stats['count']).sum()

        # Variance explained as percentage
        var_explained = (SS_between / SS_total) * 100

        # Perform ANOVA to get F-statistic and p-value
        groups = [df[df[factor] == level]['wasserstein'].values
                 for level in df[factor].unique()]
        f_stat, p_value = f_oneway(*groups)

        results.append({
            'factor': name,
            'variance_explained': var_explained,
            'f_stat': f_stat,
            'p_value': p_value,
            'significance': '***' if p_value < 0.001 else '**' if p_value < 0.01 else '*' if p_value < 0.05 else 'ns'
        })

    results_df = pd.DataFrame(results)
    results_df = results_df.sort_values('variance_explained', ascending=True)

    # Create bar plot
    fig, ax = plt.subplots(figsize=(10, 6))

    y_pos = np.arange(len(results_df))

    # Plot horizontal bars
    bars = ax.barh(y_pos, results_df['variance_explained'],
                   color='steelblue', edgecolor='black', linewidth=1, alpha=0.8)

    # Add significance stars
    for i, (idx, row) in enumerate(results_df.iterrows()):
        ax.text(row['variance_explained'] + 0.5, i, row['significance'],
               fontsize=14, fontweight='bold', va='center')

    ax.set_yticks(y_pos)
    ax.set_yticklabels(results_df['factor'], fontsize=11)
    ax.set_xlabel('Variance Explained (%)', fontsize=12, fontweight='bold')
    ax.set_title('Variance Decomposition: Factor Importance in Approximation Quality',
                fontsize=13, fontweight='bold', pad=15)
    ax.axvline(0, color='gray', linestyle='--', linewidth=1, alpha=0.5)
    ax.grid(axis='x', alpha=0.3, linestyle='--')

    # Add legend for significance
    ax.text(0.98, 0.02, '*** p<0.001  ** p<0.01  * p<0.05  ns: not significant',
           transform=ax.transAxes, fontsize=9, ha='right', va='bottom',
           bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.3))

    plt.tight_layout()
    plt.savefig(FIGURES_DIR / 'fig2_variance_decomposition_forest.png', dpi=300, bbox_inches='tight')
    plt.savefig(FIGURES_DIR / 'fig2_variance_decomposition_forest.pdf', bbox_inches='tight')
    print("  ✓ Saved: fig2_variance_decomposition_forest.png/pdf")

    plt.close()
    return results_df

variance_results = create_variance_decomposition_plot()

# ============================================================================
# FIGURE 3: Model Performance Comparison
# ============================================================================
print("\nGenerating Figure 3: Model Performance Comparison...")

def create_model_comparison():
    """
    Create grouped bar chart comparing model performance across metrics.
    """
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Left panel: Overall performance metrics
    ax1 = axes[0]
    x = np.arange(len(model_perf))
    width = 0.25

    # Normalize metrics to 0-100 scale for comparison
    wass_norm = (model_perf['wasserstein_mean'].max() - model_perf['wasserstein_mean']) / (model_perf['wasserstein_mean'].max() - model_perf['wasserstein_mean'].min()) * 100
    ks_norm = (model_perf['ks_stat_mean'].max() - model_perf['ks_stat_mean']) / (model_perf['ks_stat_mean'].max() - model_perf['ks_stat_mean'].min()) * 100
    win_rate = model_perf['win_rate']

    ax1.bar(x - width, wass_norm, width, label='Wasserstein Quality', color='#3498db', edgecolor='black', linewidth=1)
    ax1.bar(x, ks_norm, width, label='KS Quality', color='#e74c3c', edgecolor='black', linewidth=1)
    ax1.bar(x + width, win_rate, width, label='Win Rate (%)', color='#2ecc71', edgecolor='black', linewidth=1)

    ax1.set_xlabel('Model', fontsize=12, fontweight='bold')
    ax1.set_ylabel('Performance Score (0-100)', fontsize=12, fontweight='bold')
    ax1.set_title('(A) Overall Model Performance Comparison', fontsize=12, fontweight='bold', pad=10)
    ax1.set_xticks(x)
    ax1.set_xticklabels(['LLaMA 3.1\n8B', 'LLaMA 3.3\n70B', 'Qwen 2.5\n72B'], fontsize=10)
    ax1.legend(loc='upper right', framealpha=0.9)
    ax1.grid(axis='y', alpha=0.3, linestyle='--')
    ax1.set_ylim(0, 105)

    # Right panel: Performance by health status
    ax2 = axes[1]
    health_model = df_all[df_all['level'] == 'Health'].copy()
    pivot = health_model.pivot_table(index='health_level', columns='model',
                                     values='wasserstein', aggfunc='mean')
    pivot = pivot.reindex(['Good', 'Fair', 'Poor'])

    x2 = np.arange(len(pivot))
    width2 = 0.25

    for i, model in enumerate(['llama3.1_8b', 'llama3.3_70b', 'qwen2.5_72b']):
        label = model.replace('_', ' ').upper() if i == 0 else model.split('_')[0].upper() + ' ' + model.split('_')[1]
        if model == 'llama3.1_8b':
            label = 'LLaMA 3.1 8B'
        elif model == 'llama3.3_70b':
            label = 'LLaMA 3.3 70B'
        else:
            label = 'Qwen 2.5 72B'

        ax2.bar(x2 + i*width2 - width2, pivot[model], width2,
               label=label, color=list(MODEL_COLORS.values())[i],
               edgecolor='black', linewidth=1)

    ax2.set_xlabel('Health Status', fontsize=12, fontweight='bold')
    ax2.set_ylabel('Wasserstein Distance', fontsize=12, fontweight='bold')
    ax2.set_title('(B) Model Performance by Health Status', fontsize=12, fontweight='bold', pad=10)
    ax2.set_xticks(x2)
    ax2.set_xticklabels(['Good', 'Fair', 'Poor'], fontsize=10)
    ax2.legend(loc='upper left', framealpha=0.9)
    ax2.grid(axis='y', alpha=0.3, linestyle='--')

    plt.tight_layout()
    plt.savefig(FIGURES_DIR / 'fig3_model_comparison.png', dpi=300, bbox_inches='tight')
    plt.savefig(FIGURES_DIR / 'fig3_model_comparison.pdf', bbox_inches='tight')
    print("  ✓ Saved: fig3_model_comparison.png/pdf")
    plt.close()

create_model_comparison()

# ============================================================================
# FIGURE 4: Health Impact Visualization
# ============================================================================
print("\nGenerating Figure 4: Health Status Impact...")

def create_health_impact_plot():
    """
    Create detailed visualization of health status impact across countries.
    """
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle('Impact of Health Status on Approximation Quality',
                fontsize=14, fontweight='bold', y=0.995)

    # Get country-health data
    country_health = df_all[df_all['level'] == 'Country_Health'].copy()

    countries = ['USA', 'IDN', 'NLD', 'MEX']
    country_names = ['USA', 'Indonesia', 'Netherlands', 'Mexico']

    for idx, (country, name) in enumerate(zip(countries, country_names)):
        ax = axes[idx // 2, idx % 2]

        country_data = country_health[country_health['country'] == country]
        pivot = country_data.pivot_table(index='health_level', columns='questionnaire',
                                        values='wasserstein', aggfunc='mean')
        pivot = pivot.reindex(['Good', 'Fair', 'Poor'])

        # Plot grouped bars
        x = np.arange(len(pivot))
        width = 0.15
        questionnaires = ['base', 'cantril', 'ohq', 'reverse', 'swls']
        quest_labels = ['BASE', 'CANTRIL', 'OHQ', 'REVERSE', 'SWLS']
        # Use your custom questionnaire colors
        colors_quest = [QUESTIONNAIRE_COLORS[q] for q in questionnaires]

        for i, (quest, label, color) in enumerate(zip(questionnaires, quest_labels, colors_quest)):
            if quest in pivot.columns:
                offset = (i - 2) * width
                ax.bar(x + offset, pivot[quest], width, label=label,
                      color=color, edgecolor='black', linewidth=0.8)

        ax.set_xlabel('Health Status', fontsize=10, fontweight='bold')
        ax.set_ylabel('Wasserstein Distance', fontsize=10, fontweight='bold')
        ax.set_title(f'{name}', fontsize=11, fontweight='bold', pad=8)
        ax.set_xticks(x)
        ax.set_xticklabels(['Good', 'Fair', 'Poor'], fontsize=9)
        if idx == 1:
            ax.legend(loc='upper left', fontsize=8, ncol=2, framealpha=0.9)
        ax.grid(axis='y', alpha=0.3, linestyle='--')
        ax.set_ylim(0, max(4.5, pivot.values.max() * 1.1))

    plt.tight_layout()
    plt.savefig(FIGURES_DIR / 'fig4_health_impact.png', dpi=300, bbox_inches='tight')
    plt.savefig(FIGURES_DIR / 'fig4_health_impact.pdf', bbox_inches='tight')
    print("  ✓ Saved: fig4_health_impact.png/pdf")
    plt.close()

create_health_impact_plot()

# ============================================================================
# Print Summary
# ============================================================================
print("\n" + "="*70)
print("FIGURE GENERATION COMPLETE")
print("="*70)
print("\nGenerated Files:")
print("\nFigures (Outputs/plots/subgroup_analysis/):")
print("  - fig1_comprehensive_heatmap.png/pdf")
print("  - fig2_variance_decomposition_forest.png/pdf")
print("  - fig3_model_comparison.png/pdf")
print("  - fig4_health_impact.png/pdf")
print("\nNote: Tables are generated by subgroup_analysis.py")
print("\n" + "="*70)
